---
- name: Check Server_stats
  hosts: all
  tasks:
    - name: Check memory
      command: free -m
      register: free_output
    
    - name: Print output of check memory statement
      debug:
        var: free_output
    
    - name: Check disk
      command: df -h
      register: disk_output
    
    - name: Print output of check disk statement
      debug:
        var: disk_output
      